### ISSUE TITLE
Failed to load a runtime custom widget, it may have been compiled for a different Cumulocity version.

### ISSUE THREAD

**Issue by tchainaf** [SoftwareAG/cumulocity-smart-map-widget#1]
I can't upload the widget to my cockpit, after refreshing the page I get this message: "Failed to load a runtime custom widget, it may have been compiled for a different Cumulocity version."

On Developer Tools console, I get this:
![image](https://user-images.githubusercontent.com/33184530/106304688-6cec9000-623a-11eb-8234-0c1becb5cb97.png)

My cockpit version is 1006.6.8 and I loaded some other widgets (like [Silo Capacity](https://github.com/SoftwareAG/cumulocity-silo-capacity-widget)) without any problems

**Comment by DarpanLalani** [comment]
Could you please try with latest version and let me know if problem persist.

**Comment by DarpanLalani** [comment]
Closing since no more activity in this issue.
