### ISSUE TITLE
Smart Map with map type cluster is faining with error  "Cannot read properties of undefined (reading 'lat')"

### ISSUE THREAD

**Issue by IrfanaSabreen** [SoftwareAG/cumulocity-smart-map-widget#8]
In vaccine distribution demo - smart map with cluster type enabled is failing with error "Cannot read properties of undefined (reading 'lat')" 
App builder version - 1.2.6
Smart map widget version - 1.0.5

**Comment by YashPShah-swag** [comment]
Fixed.
