### ISSUE TITLE
Documentation rendering in Widget catalog is broken

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-smart-map-widget#9]
See below screenshot:

* Entry 5 is only showing the closing bracket of the restriction that this works only for indoor maps
* Entry 8 formatting is broken due to usage of a link in Readme.md

![image](https://user-images.githubusercontent.com/44459397/202847683-ff1fccef-bd08-43a8-8b6c-591c5c3bbb96.png)

**Comment by YashPShah-swag** [comment]
Resolved.
